create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  title text not null,
  description text,
  deadline timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  title text not null,
  exam_date timestamptz not null,
  location text not null,
  type text not null default 'midterm' check (type in ('midterm', 'final', 'quiz')),
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists assignments_lesson_id_idx on public.assignments (lesson_id);
create index if not exists exams_lesson_id_idx on public.exams (lesson_id);

alter table public.assignments enable row level security;
alter table public.exams enable row level security;

-- Policies for assignments
drop policy if exists "assignments readable by scoped users" on public.assignments;
create policy "assignments readable by scoped users"
on public.assignments
for select
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or l.teacher_id = auth.uid()
         or (
           public.current_user_role() = 'student'
           and l.group_id = public.current_user_group_id()
         )
       )
  )
);

drop policy if exists "teachers can create scoped assignments" on public.assignments;
create policy "teachers can create scoped assignments"
on public.assignments
for insert
to authenticated
with check (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers can update scoped assignments" on public.assignments;
create policy "teachers can update scoped assignments"
on public.assignments
for update
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers can delete scoped assignments" on public.assignments;
create policy "teachers can delete scoped assignments"
on public.assignments
for delete
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

-- Policies for exams
drop policy if exists "exams readable by scoped users" on public.exams;
create policy "exams readable by scoped users"
on public.exams
for select
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or l.teacher_id = auth.uid()
         or (
           public.current_user_role() = 'student'
           and l.group_id = public.current_user_group_id()
         )
       )
  )
);

drop policy if exists "teachers can create scoped exams" on public.exams;
create policy "teachers can create scoped exams"
on public.exams
for insert
to authenticated
with check (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers can update scoped exams" on public.exams;
create policy "teachers can update scoped exams"
on public.exams
for update
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers can delete scoped exams" on public.exams;
create policy "teachers can delete scoped exams"
on public.exams
for delete
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);
