create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.teachers_whitelist (
  email text primary key,
  is_super boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  name text not null,
  role text not null check (role in ('student', 'teacher')),
  is_super boolean not null default false,
  group_id bigint references public.groups(id) on delete set null,
  university text,
  program text,
  course_year text,
  bio text,
  gpa double precision,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  subject text not null,
  teacher_id uuid not null references public.users(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  start_time timestamptz not null,
  end_time timestamptz not null,
  room text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint lessons_time_range_check check (end_time > start_time)
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  title text not null,
  file_url text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists users_group_id_idx on public.users (group_id);
create index if not exists users_role_idx on public.users (role);
create index if not exists lessons_teacher_id_idx on public.lessons (teacher_id);
create index if not exists lessons_group_id_idx on public.lessons (group_id);
create index if not exists lessons_start_time_idx on public.lessons (start_time);
create index if not exists materials_lesson_id_idx on public.materials (lesson_id);
create index if not exists materials_created_at_idx on public.materials (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists lessons_set_updated_at on public.lessons;
create trigger lessons_set_updated_at
before update on public.lessons
for each row
execute function public.set_updated_at();

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.users
  where id = auth.uid()
$$;

create or replace function public.current_user_is_super()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(is_super, false)
  from public.users
  where id = auth.uid()
$$;

create or replace function public.current_user_group_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select group_id
  from public.users
  where id = auth.uid()
$$;

create or replace function public.handle_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text;
  effective_role text;
  requested_group_name text;
  resolved_group_id bigint;
  whitelist_super boolean := false;
  resolved_name text;
begin
  requested_role := lower(coalesce(new.raw_user_meta_data ->> 'role', 'student'));
  effective_role := case
    when requested_role = 'teacher' then 'teacher'
    else 'student'
  end;

  requested_group_name := nullif(trim(coalesce(new.raw_user_meta_data ->> 'group', '')), '');
  if requested_group_name is not null then
    select g.id
      into resolved_group_id
      from public.groups g
     where lower(g.name) = lower(requested_group_name)
     limit 1;
  end if;

  select coalesce(tw.is_super, false)
    into whitelist_super
    from public.teachers_whitelist tw
   where lower(tw.email) = lower(new.email)
   limit 1;

  resolved_name := nullif(trim(coalesce(new.raw_user_meta_data ->> 'name', '')), '');
  if resolved_name is null then
    resolved_name := split_part(coalesce(new.email, ''), '@', 1);
  end if;

  insert into public.users (
    id,
    email,
    name,
    role,
    is_super,
    group_id,
    university,
    program,
    course_year
  )
  values (
    new.id,
    coalesce(new.email, ''),
    resolved_name,
    effective_role,
    whitelist_super,
    case when effective_role = 'student' then resolved_group_id else null end,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'university', '')), ''),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'faculty', '')), ''),
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'course_year', '')), '')
  )
  on conflict (id) do update
    set email = excluded.email,
        name = excluded.name,
        role = excluded.role,
        is_super = public.users.is_super or excluded.is_super,
        group_id = coalesce(excluded.group_id, public.users.group_id),
        university = excluded.university,
        program = excluded.program,
        course_year = excluded.course_year;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_auth_user();

alter table public.groups enable row level security;
alter table public.users enable row level security;
alter table public.lessons enable row level security;
alter table public.materials enable row level security;

drop policy if exists "groups are readable" on public.groups;
create policy "groups are readable"
on public.groups
for select
to anon, authenticated
using (true);

drop policy if exists "users are readable to authenticated clients" on public.users;
create policy "users are readable to authenticated clients"
on public.users
for select
to authenticated
using (true);

drop policy if exists "users insert own row" on public.users;
create policy "users insert own row"
on public.users
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "users update own row" on public.users;
create policy "users update own row"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "users delete own row" on public.users;
create policy "users delete own row"
on public.users
for delete
to authenticated
using (auth.uid() = id or public.current_user_is_super());

drop policy if exists "lessons are readable by role scope" on public.lessons;
create policy "lessons are readable by role scope"
on public.lessons
for select
to authenticated
using (
  public.current_user_is_super()
  or teacher_id = auth.uid()
  or (
    public.current_user_role() = 'student'
    and group_id = public.current_user_group_id()
  )
);

drop policy if exists "teachers create scoped lessons" on public.lessons;
create policy "teachers create scoped lessons"
on public.lessons
for insert
to authenticated
with check (
  public.current_user_is_super()
  or (
    public.current_user_role() = 'teacher'
    and teacher_id = auth.uid()
  )
);

drop policy if exists "teachers update scoped lessons" on public.lessons;
create policy "teachers update scoped lessons"
on public.lessons
for update
to authenticated
using (
  public.current_user_is_super()
  or (
    public.current_user_role() = 'teacher'
    and teacher_id = auth.uid()
  )
)
with check (
  public.current_user_is_super()
  or (
    public.current_user_role() = 'teacher'
    and teacher_id = auth.uid()
  )
);

drop policy if exists "teachers delete scoped lessons" on public.lessons;
create policy "teachers delete scoped lessons"
on public.lessons
for delete
to authenticated
using (
  public.current_user_is_super()
  or (
    public.current_user_role() = 'teacher'
    and teacher_id = auth.uid()
  )
);

drop policy if exists "materials are readable by lesson scope" on public.materials;
create policy "materials are readable by lesson scope"
on public.materials
for select
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or l.teacher_id = auth.uid()
         or (
           public.current_user_role() = 'student'
           and l.group_id = public.current_user_group_id()
         )
       )
  )
);

drop policy if exists "teachers create scoped materials" on public.materials;
create policy "teachers create scoped materials"
on public.materials
for insert
to authenticated
with check (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers update scoped materials" on public.materials;
create policy "teachers update scoped materials"
on public.materials
for update
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
)
with check (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

drop policy if exists "teachers delete scoped materials" on public.materials;
create policy "teachers delete scoped materials"
on public.materials
for delete
to authenticated
using (
  exists (
    select 1
      from public.lessons l
     where l.id = lesson_id
       and (
         public.current_user_is_super()
         or (
           public.current_user_role() = 'teacher'
           and l.teacher_id = auth.uid()
         )
       )
  )
);

insert into storage.buckets (id, name, public)
values ('materials', 'materials', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "materials bucket is readable" on storage.objects;
create policy "materials bucket is readable"
on storage.objects
for select
to public
using (bucket_id = 'materials');

drop policy if exists "teachers upload materials objects" on storage.objects;
create policy "teachers upload materials objects"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'materials'
  and (
    public.current_user_is_super()
    or split_part(name, '/', 1) = auth.uid()::text
  )
);

drop policy if exists "teachers update materials objects" on storage.objects;
create policy "teachers update materials objects"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'materials'
  and (
    public.current_user_is_super()
    or split_part(name, '/', 1) = auth.uid()::text
  )
)
with check (
  bucket_id = 'materials'
  and (
    public.current_user_is_super()
    or split_part(name, '/', 1) = auth.uid()::text
  )
);

drop policy if exists "teachers delete materials objects" on storage.objects;
create policy "teachers delete materials objects"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'materials'
  and (
    public.current_user_is_super()
    or split_part(name, '/', 1) = auth.uid()::text
  )
);
