create table if not exists public.user_stories (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.users(id) on delete cascade,
  border_color text,
  media_url text, -- optional for now
  created_at timestamptz not null default timezone('utc', now()),
  expires_at timestamptz not null default timezone('utc', now() + interval '24 hours')
);

create index if not exists user_stories_author_id_idx on public.user_stories (author_id);
create index if not exists user_stories_expires_at_idx on public.user_stories (expires_at);

alter table public.user_stories enable row level security;

drop policy if exists "user stories are readable to authenticated users" on public.user_stories;
create policy "user stories are readable to authenticated users"
on public.user_stories
for select
to authenticated
using (expires_at > timezone('utc', now()));

drop policy if exists "users can insert own stories" on public.user_stories;
create policy "users can insert own stories"
on public.user_stories
for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "users can delete own stories" on public.user_stories;
create policy "users can delete own stories"
on public.user_stories
for delete
to authenticated
using (author_id = auth.uid());
